gems:
  - jekyll-seo-tag
title: Stranger Guy
description: Website inspired by «Stranger Things» TV series & «Tourette's Guy» YouTube videos
url: suburbs.github.io/strangerguy
logo: /img/sg_logo_280.png
image: /img/page-pic.jpg
